import { Component, OnInit } from '@angular/core';

declare var $: any;

@Component({
	selector: 'all-grid',
	templateUrl: './all.component.html'
})

export class AllComponent implements OnInit {

	topBars: object = {};
	topTrs: object = {};
	bottomTrs: object = {};

	bodyTds: object = {};

	constructor() { 

		this.topBars = [

			{ mClass: 'top_Bar_Msg', msg: 'Drag a column header and drop it here to group by that column' },
			{ mClass: 'top_Bar_Btn', msg: 'Delete Selected' },
			{ mClass: 'top_Bar_Btn', msg: 'Export to Excel' }
		],

		this.topTrs = [

			{ mClass: 'PosFull border-left th_full', val: 'Pos' },
			{ mClass: 'th_Null', val: '' },
			{ mClass: 'th_full', val: 'Alert' },
			{ mClass: 'th_full', val: 'LeadId' },
			{ mClass: 'th_full', val: 'Source' },
			{ mClass: 'th_full', val: 'Tracking Summary' },
			{ mClass: 'th_full', val: 'Pix' },
			{ mClass: 'th_full', val: 'Product' },
			{ mClass: 'th_full', val: 'FirstName' },
			{ mClass: 'th_full', val: 'LastName' },
			{ mClass: 'th_full', val: 'Landline' },
			{ mClass: 'th_full', val: 'Email' },
			{ mClass: 'th_full', val: 'Created On' },
			{ mClass: 'th_full', val: 'Website Url' },
			{ mClass: 'TransfFull border-right th_full', val: 'Transferred To' }
		],

		this.bottomTrs = [

			{ mClass: 'Pos_Inp border-left th_full' },
			{ mClass: 'th_Null' },
			{ mClass: 'noInput th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'noInput th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'th_full' },
			{ mClass: 'noInput th_full' },
			{ mClass: 'noInput th_full' },
			{ mClass: 'border-right th_full' }
		],

		this.bodyTds = [

			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/leads',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backWhite',
				name1: 'Transferred',
				mainClass2: 'td_Null backWhite',
				name2: '',
				mainClass3: 'td_full backWhite',
				name3: '',
				mainClass4: 'td_full backWhite',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backWhite',
				name5: 'Affiliate',
				mainClass6: 'td_full backWhite',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backWhite',
				name7: 'Yes',
				mainClass8: 'td_full backWhite',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backWhite',
				name9: 'Christine',
				mainClass10: 'td_full backWhite',
				name10: 'Greenwell',
				mainClass11: 'td_full backWhite',
				name11: '01914775977',
				mainClass12: 'td_full backWhite',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backWhite',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backWhite',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backWhite',
				name15: ''
			},
			{ 
				mainClass1: 'td_full border-left backGrey',
				name1: 'Transferred',
				mainClass2: 'td_Null backGrey',
				name2: '',
				mainClass3: 'td_full backGrey',
				name3: '',
				mainClass4: 'td_full backGrey',
				name4: '2763853',
				url4: '/',
				mainClass5: 'td_full backGrey',
				name5: 'Affiliate',
				mainClass6: 'td_full backGrey',
				name6: '168',
				name6a: '27',
				name6b: '6H Media',
				mainClass7: 'td_full backGrey',
				name7: 'Yes',
				mainClass8: 'td_full backGrey',
				name8: 'Funeral Plan',
				mainClass9: 'td_full backGrey',
				name9: 'Christine',
				mainClass10: 'td_full backGrey',
				name10: 'Greenwell',
				mainClass11: 'td_full backGrey',
				name11: '01914775977',
				mainClass12: 'td_full backGrey',
				name12: 'chriswell@hotmail.com',
				mainClass13: 'td_full backGrey',
				name13: '10/07/201811:44:43',
				mainClass14: 'td_full backGrey',
				name14: 'yourhealthcovered.co.uk',
				mainClass15: 'td_full border-right backGrey',
				name15: ''
			}
		]

	}

	ngOnInit() {}

	ngAfterViewInit() {}

}
